title: Lineae ex punctis
description: a blog about patterns in data
github: https://github.com/ex-punctis?tab=repositories
show_downloads: false
google_analytics: UA-119294497-1

plugins:
  - jekyll-seo-tag